-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    -   id: check-json
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
-   repo: local
    hooks:
        -   id: yapf
            name: yapf
            entry: yapf
            language: python
            args: ["-i", "-p"]
            exclude: ^docs/conf.py$
            types: [python]
            additional_dependencies: ['yapf']
