---
language: python
env:
  - TENV=py36
  - TENV=itest
python:
  - 3.6
install: pip install tox
script: tox -e $TENV

deploy:
  - provider: pypi
    user: yelplabs
    password:
      secure: "ZUQHl9BldAntIwEz9QPf5rODpGwb/2M+Bjs3scFuGBK8PsDtZ9krek9TsDsLEIw7IjQw9eUc25xcDZ5DsIXLF+aZLGeEkBrKkPzPMBD9ebWH8phtINg5H1tgMbtWmieDI1SGcPXoSQhOpaKG3v0FrbdTb1V5DNVFqawn0rvFJ8U="
    on:
      tags: true
      repo: Yelp/Tron
      condition: $TENV == "py36"
