---
language: python
env:
  - TARGET=tox_py27
  - TARGET=tox_py36
  - TARGET=debitest_trusty
python:
  - 2.7
  - 3.6

before_install:
  - sudo apt-get install -y libdb5.3-dev

install: pip install tox
script: make $TARGET

matrix:
  exclude:
    - env: TARGET=tox_py36
      python: 2.7
    - env: TARGET=tox_py27
      python: 3.6
    - env: TARGET=debitest_trusty
      python: 3.6

deploy:
  - provider: pypi
    user: yelplabs
    password:
      secure: "ZUQHl9BldAntIwEz9QPf5rODpGwb/2M+Bjs3scFuGBK8PsDtZ9krek9TsDsLEIw7IjQw9eUc25xcDZ5DsIXLF+aZLGeEkBrKkPzPMBD9ebWH8phtINg5H1tgMbtWmieDI1SGcPXoSQhOpaKG3v0FrbdTb1V5DNVFqawn0rvFJ8U="
    on:
      tags: true
      repo: Yelp/Tron
      condition: $TARGET == "tox_py36"
