--- !TronConfiguration
ssh_options: !SSHOptions
    agent: true

nodes:
    - &batch4 !Node
        hostname: batch4

jobs:
    - &jobFlow !JobFlow
        name: "ad_simulation"
        node: *batch4
        schedule: "daily"
        jobs:
            - &removeScoreLogs !Job
                name: "rm_score_logs"
                command: 'find $BATCH_DIR/logs/score -ctime +9 -name "scores_*.log" | xargs --no-run-if-empty rm'
            - &dumpGeocache !Job
                name: "dump_geocache"
                command: "$PYTHON $BATCH_DIR/ads/dump_geocache.py"
            - &rebuildDatabase !Job
                name: "rebuild_database"
                command: "rm -f /nail/tmp/sim.db; $PYTHON $BATCH_DIR/adsim/build_sqlite_category.py /nail/tmp/sim.db"
            - &simulate !Job
                name: "simulate"
                command: "$PYTHON $BATCH_DIR/simulate_ad_delivery.py -s 7 -x 10 -m simopt --replace --update --with-sqlite-db=/nail/tmp/sim.db --fork --init-weights"
                requires:
                    - *removeScoreLogs
                    - *dumpGeocache
                    - *rebuildDatabase

