---

jobs:

services:
  -  name: "pretend_tron_service_1"
     owner: "vagrant@localhost"
     summary: "Testing a service that runs on many nodes"
     notes: |
       runs on weighted nodes, so we should have many more on batch-01 than
       on the other nodes.

       how does a second paragraph break things?
     node: "weighted_pool"
     count: 20
     monitor_interval: 30
     restart_delay: 60
     pid_file: "/tmp/%(name)s-%(instance_number)s.pid"
     command: "/vagrant/vagrant/pretend_tron_service.sh %(pid_file)s 10"
