state_persistence:
    name: "/nail/tron/tron_state"
    store_type: "shelve"
    buffer_size: 10

ssh_options:
   agent: False
   identities:
      - /work/example-cluster/insecure_key

action_runner:
    runner_type: "subprocess"
    remote_status_path: "/tmp/tron"
    remote_exec_path: "/work/bin/"

nodes:
   - hostname: localhost
     username: tron

time_zone: US/Eastern

jobs:
  - name: "test"
    node: localhost
    schedule: "cron * * * * *"
    time_zone: "US/Pacific"
    actions:
      - name: "first"
        command: "date; ruby -e 'exit(rand(0..1))'"
        retries: 3
    cleanup_action:
      command: "echo %(last_success:shortdate)s %(cleanup_job_status)s"
