version: "3"
services:
  master:
    build:
      context: ../
      dockerfile: example-cluster/images/batch/Dockerfile
    volumes:
      - ../:/work
      - ./:/nail/tron
    links:
      - batch1
  batch1:
    build:
      context: ../
      dockerfile: example-cluster/images/batch/Dockerfile
