version: "3"
services:
  master:
    build:
      context: ../
      # dockerfile: Dockerfile.trusty
      dockerfile: Dockerfile.xenial
    volumes:
      - ../:/work
      - ./:/var/lib/tron
    links:
      - batch1
      - batch2
  batch1:
    build:
      context: images/batch
  batch2:
    build:
      context: images/batch
