version: "3"
services:
  # For debugging
  playground:
    build:
      context: ../
      dockerfile: yelp_package/xenial/${DOCKERFILE_PREFIX}Dockerfile
    volumes:
      - ../:/work
      - ./:/nail/tron
    ports:
      - "8089:8089"
  # For itests only, `pip install -e .` won't work
  master:
    build:
      context: .
      dockerfile: example-cluster/images/master/${DOCKERFILE_PREFIX}Dockerfile
    links:
      - batch1
  batch1:
    build:
      context: ../
      dockerfile: example-cluster/images/batch/${DOCKERFILE_PREFIX}Dockerfile
