version: "3"
services:
  master:
    build:
      context: ../
    volumes:
      - ../:/work
      - ./:/nail/tron
    links:
      - batch1
      - batch2
  batch1:
    build:
      context: images/batch
  batch2:
    build:
      context: images/batch
