version: "3"
services:
  # For debugging
  playground:
    build:
      context: ../
      dockerfile: yelp_package/trusty/Dockerfile
      # dockerfile: yelp_package/xenial/Dockerfile
    volumes:
      - ../:/work
      - ./:/nail/tron
    links:
      - batch1
      - batch2
  # For itests only, `pip install -e .` won't work
  master:
    build:
      context: .
      dockerfile: ubuntu:trusty
      # dockerfile: images/xenial
    links:
      - batch1
      - batch2
  batch1:
    build:
      context: images/batch
  batch2:
    build:
      context: images/batch
