eventbus_enabled: true

state_persistence:
  name: "/nail/tron/tron_state"
  store_type: "shelve"
  buffer_size: 10

ssh_options:
  agent: False
  identities:
    - /work/example-cluster/insecure_key

action_runner:
  runner_type: "subprocess"
  remote_status_path: "/tmp/tron"
  remote_exec_path: "/work/tron/bin/"

nodes:
  - hostname: localhost
    username: root

time_zone: US/Eastern

jobs:
  - name: "one"
    node: localhost
    schedule: "cron * * * * *"
    time_zone: "US/Pacific"
    actions:
      - name: "one"
        command: "exit $((RANDOM % 2))"
        trigger_downstreams:
          ymdhm: "{ymdhm}"
        retries: 3
  - name: "two"
    node: localhost
    schedule: "cron * * * * *"
    time_zone: "US/Pacific"
    actions:
      - name: "two"
        command: "exit $((RANDOM % 2))"
        triggered_by: ["MASTER.one.one.ymdhm.{ymdhm}"]
        trigger_timeout: 5s
