ssh_options:
   agent: False
   identities:
      - /work/example-cluster/insecure_key

action_runner:
    runner_type: "subprocess"
    remote_status_path: "/tmp/tron"
    remote_exec_path: "/work/bin/"

nodes:
   - hostname: localhost
     username: tron
# Note: the action runner is not available on batch1.
# Comment out the action_runner config if you want to schedule things remotely
   - hostname: batch1
     username: tron

time_zone: US/Eastern

jobs:
   - name: "test"
     node: localhost
     schedule: "daily 17:00:00"
     time_zone: "US/Pacific"
     actions:
        - name: "first"
          command: "sleep 5m"
