state_persistence:
  name: "/tmp/tron_state"
  table_name: "-tmp-tron_state"
  store_type: "dynamodb"
  buffer_size: 10
  dynamodb_region: us-west-1

ssh_options:
   agent: False

nodes:
  - hostname: localhost

mesos_options:
  master_address: mesos.paasta-mesosstage.yelp
  master_port: 5050
  role: '*'
  enabled: True
  dockercfg_location: file:///root/.dockercfg

jobs:
    - name: "test"
      node: localhost
      schedule: "interval 1m"
      actions:
        - name: "first"
          command: "echo 'hello world'"
          cpus: 1
          mem: 100
