--- !TronConfiguration
working_dir: "/Users/mtytel/Tron/working"

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node0
        hostname: 'dev2sv'
    - &node1
        hostname: 'dev3sv'

    - &node_pool !NodePool
        nodes: [*node0, *node1]

jobs:
    -
        name: "interval_dag"
        node: *node0
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &dag0
                name: "dag0"
                command: "sleep 3; echo 0"
            - &dag1
                name: "dag1"
                command: "sleep 3; echo 1"
                requires: *dag0
            - &dag2
                name: "dag2"
                command: "sleep 3; echo 2"
                requires: *dag0
            -
                name: "dag3"
                command: "sleep 1; echo 3"
                requires: [*dag1, *dag2]

    -
        name: "fail_dag"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &action_fail
                name: "action_test_fail1"
                command: "sleep 5;failfailfail"
            -
                name: "cancel0"
                requires: *action_fail
                command: "sleep 1; echo cancelled; sleep 1"
            -
                name: "cancel1"
                requires: *action_fail
                command: "sleep 1; echo cancelled; sleep 1"

    -
        name: "constant"
        node: *node_pool
        schedule: "constant"
        actions:
            - &action_const0
                name: "constant_lead0"
                command: "sleep 5; echo constant; sleep 2"
            - &action_const1
                name: "different_node"
                node: *node0
                command: "sleep 1; echo following; sleep 2"
            - &actionFoll
                name: "follow"
                command: "sleep 1; echo following; sleep 2"
                requires: [*action_const0, *action_const1]
            
    -
        name: "daily_mws"
        node: *node_pool
        schedule: "MWS" # All Days: MTWRFSU
        actions:
            - &actionMF
                name: "action_mws"
                command: "sleep 5; echo mws; sleep 2"

    -
        name: "daily"
        node: *node_pool
        schedule: "daily"
        actions:
            - &actionDaily
                name: "action_daily"
                command: "sleep 5; echo daily; sleep 2"

    -
        name: "queueing"
        node: *node_pool
        queueing: True
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - !Action
                name: "long_action"
                command: "sleep 10; echo queueing; sleep 10"

    -
        name: "cancel"
        node: *node0
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            -
                name: "actionCancel"
                command: "sleep 10; echo cancelnext; sleep 10"

    -
        name: "fail_queue"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - &actionFailQueue
                name: "actionFailQueue1"
                command: "sleep 15; failfailfail"

    -
        name: "all_nodes"
        node: *node_pool
        all_nodes: True
        schedule: !IntervalScheduler
            interval: 50s
        actions:
            - &actionAddition
                name: "all_node0"
                command: "sleep 4; echo im awake"
            - &acitonWait
                name: "all_node1"
                command: "sleep 2; echo jobs done"

services:
    - 
        name: "service0"
        node: *node_pool
        enable:
            command: "sleep 4; echo enabled"
        disable:
            command: "sleep 5; echo disabled"
        monitor:
            schedule: !IntervalScheduler
                interval: 40s
            actions:
                - &mon0
                    name: "mon0"
                    command: "sleep 4; echo mon0"
                -
                    name: "mon1"
                    command: "sleep1; echo mon1"
                    requires: *mon0
        
