--- !TronConfiguration
working_dir: './working'

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node1 !Node
        hostname: 'dev2sv'
    - &node2 !Node
        hostname: 'dev3sv'

    - &pool !NodePool
        nodes: [*node1, *node2]

jobs:
    - &job0 !Job
        name: "job0"
        node: *pool
        all_nodes: True
        schedule: !IntervalScheduler
            interval: 20s
        queueing: False
        actions:
            - &start !Action
                name: "actionStartEdit"
                command: "sleep 3; echo asdfasdf"
                node: *node

    - &job1 !Job
        name: "job1"
        node: *node
        schedule: !IntervalScheduler
            interval: 30s
        queueing: False
        actions:
            - &action !Action
                name: "actionAlone"
                command: "cat big.txt; sleep 10"
services:
    - &servOne !Service
        name: "testserv"
        node: *pool
        enable: !Action
            name: "enableaction"
            command: "sleep 10; echo one"
        monitor:
            actions:
                - !Action
                    name: "actionMo"
                    command: "echo hello; sleep 5"
            schedule: !IntervalScheduler
                interval: 20s
                command: "python test.py"

