--- !TronConfiguration
working_dir: './working'

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node !Node
        hostname: 'dev4sv'
    - &pool !NodePool
        hostnames: ['dev2sv', 'dev3sv']

jobs:
    - &job0 !Job
        name: "job0"
        node: *pool
        schedule: !IntervalScheduler
            interval: 20s
        queueing: False
        actions:
            - &start !Action
                name: "actionStartEdit"
                command: "sleep 3; echo asdfasdf"
                node: *node

services:
    - &servOne !Service
        name: "testserv"
        node: *pool
        enable: !Action
            name: "enableaction"
            command: "sleep 10; echo one"
        monitor:
            actions:
                - !Action
                    name: "actionMo"
                    command: "echo hello; sleep 5"
            schedule: !IntervalScheduler
                interval: 20s

