--- !TronConfiguration
working_dir: "/Users/mtytel/Tron/working"

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node0 !Node
        hostname: 'dev4sv'
    - &node_pool !NodePool
        hostnames: ['dev3sv', 'dev4sv']

jobs:
    - !Job
        name: "interval_dag"
        node: *node0
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &dag0 !Action
                name: "dag0"
                command: "sleep 3; echo 0"
            - &dag1 !Action
                name: "dag1"
                command: "sleep 3; echo 1"
                requires: *dag0
            - &dag2 !Action
                name: "dag2"
                command: "sleep 3; echo 2"
                requires: *dag0
            - !Action
                name: "dag3"
                command: "sleep 1; echo 3"
                requires: [*dag1, *dag2]

    - !Job
        name: "fail_dag"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &succ0 !Action
                name: "succ0"
                command: "sleep 5; echo start"
            - &succ1 !Action
                name: "succ1"
                requires: *succ0
                command: "sleep 1; echo cancelled; sleep 1"
            - &fail !Action
                name: "fail"
                requires: *succ0
                command: "sleep 4; echo cancelled; fdsadsfaeafaefa"
            - !Action
                name: "end"
                requires: [*succ1, *fail]
                command: "sleep 5; echo done"

    - !Job
        name: "constant"
        node: *node_pool
        schedule: "constant"
        actions:
            - &action_const0 !Action
                name: "constant_lead0"
                command: "sleep 5; echo constant; sleep 2"
            - &action_const1 !Action
                name: "different_node"
                node: *node0
                command: "sleep 1; echo following; sleep 2"
            - &actionFoll !Action
                name: "follow"
                command: "sleep 1; echo following; sleep 2"
                requires: [*action_const0, *action_const1]
            
    - !Job
        name: "daily_mws"
        node: *node_pool
        schedule: "MWS" # All Days: MTWRFSU
        actions:
            - &actionMF !Action
                name: "action_mws"
                command: "sleep 5; echo mws; sleep 2"

    - !Job
        name: "daily"
        node: *node_pool
        schedule: "daily"
        actions:
            - &actionDaily !Action
                name: "action_daily"
                command: "sleep 5; echo daily; sleep 2"

    - !Job
        name: "queueing"
        node: *node_pool
        queueing: True
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - !Action
                name: "long_action"
                command: "sleep 10; echo queueing; sleep 10"

    - !Job
        name: "cancel"
        node: *node0
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - !Action
                name: "actionCancel"
                command: "sleep 10; echo cancelnext; sleep 10"

    - !Job
        name: "fail_queue"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - &actionFailQueue !Action
                name: "actionFailQueue1"
                command: "sleep 15; failfailfail"

    - !Job
        name: "all_nodes"
        node: *node_pool
        all_nodes: True
        schedule: !IntervalScheduler
            interval: 50s
        actions:
            - &actionAddition !Action
                name: "all_node0"
                command: "sleep 4; echo im awake"
            - &acitonWait !Action
                name: "all_node1"
                command: "sleep 2; echo jobs done"

services:
    - !Service
        name: "service0"
        node: *node_pool
        enable: !Action
            name: "enable"
            command: "sleep 4; echo enabled"
        disable: !Action
            name: "disable"
            command: "sleep 5; echo disabled"
        monitor:
            schedule: !IntervalScheduler
                interval: 40s
            actions:
                - &mon0 !Action
                    name: "mon0"
                    command: "sleep 4; echo mon0"
                - !Action
                    name: "mon1"
                    command: "sleep1; echo mon1"
                    requires: *mon0
        
