--- !TronConfiguration
working_dir: './working'

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node1 !Node
        hostname: 'dev2sv'
    - &node2 !Node
        hostname: 'dev3sv'

    - &pool !NodePool
        nodes: [*node1, *node2]

jobs:
    - &job0 !Job
        name: "job0"
        node: *pool
        all_nodes: True
        schedule: "interval 20s"
        queueing: False
        actions:
            - &start
                name: "actionStartEdit"
                command: "sleep 3; echo asdfasdf"
                node: *node

    - &job1 !Job
        name: "job1"
        node: *node
        schedule: "interval 20s"
        queueing: False
        actions:
            - &action !Action
                name: "actionAlone"
                command: "cat big.txt; sleep 10"
services:
    -
        name: "testserv"
        node: *pool
        enable:
            command: "sleep 10; echo one"
        monitor:
            actions:
                - 
                    name: "actionMo"
                    command: "echo hello; sleep 5"
            schedule: "interval 20s"

