--- !TronConfiguration
working_dir: "/Users/mtytel/Tron/working"

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node0 !Node
        hostname: 'dev4sv'
    - &node_pool !NodePool
        hostnames: ['dev3sv', 'dev4sv']

jobs:
    - &intJob !Job
        name: "interval0a"
        node: *node0
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &intAction0 !Action
                name: "actionInterval00"
                command: "sleep 3; echo 4"
            - &intAction1 !Action
                name: "actionInterval01"
                command: "sleep 3; echo 4"
                requires: *intAction0
            - &intAction2 !Action
                name: "actionInterval02"
                command: "sleep 3; echo 4"
                requires: *intAction0
    - &jobFoo !Job
        name: "interval0b"
        node: *node0
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &actionFoo !Action
                name: "actionInterval0b"
                command: "python test.py"
            - &actionBar !Action
                name: "actionFollow"
                command: "echo 1;sleep 5;easdfasdfdscho 2"
                requires: *actionFoo

    - &jobFail !Job
        name: "testfail1"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 20s
        actions:
            - &actionFail !Action
                name: "actionTestFail1"
                command: "sleep 5;failfailfail"
            - &actionCanc !Action
                name: "actionCanc"
                requires: *actionFail
                command: "sleep 1; echo Canc; sleep 1"

    - &jobConstant !Job
        name: "constant1"
        node: *node_pool
        schedule: "constant"
        actions:
            - &actionConstant0 !Action
                name: "constantLeader0"
                command: "sleep 5; echo constant; sleep 2"
            - &actionConstant1 !Action
                name: "constantLeader1"
                node: *node0
                command: "sleep 1; echo following; sleep 2"
            - &actionFoll !Action
                name: "follow0"
                command: "sleep 1; echo following; sleep 2"
                requires: [*actionConstant0, *actionConstant1]
            
    - &jobMF !Job
        name: "dailyMF"
        node: *node_pool
        schedule: "MS"
        actions:
            - &actionMF !Action
                name: "actionMF"
                command: "sleep 5;echo mf; sleep 2"

    - &jobDaily !Job
        name: "daily1"
        node: *node_pool
        schedule: "daily"
        actions:
            - &actionDaily !Action
                name: "actionDaily1"
                command: "sleep 5;echo daily1; sleep 2"

    - &jobQueue !Job
        name: "queueing1"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - &actionQueue !Action
                name: "actionQueueing1"
                command: "sleep 10; echo queueing; sleep 10"

    - &jobCancel !Job
        name: "cancel0"
        node: *node0
        queueing: False
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - &actionCancel !Action
                name: "actionCancel"
                command: "sleep 10; echo cancelnext; sleep 10"

    - &jobFailQueue !Job
        name: "failqueue1"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - &actionFailQueue !Action
                name: "actionFailQueue1"
                command: "sleep 15; failfailfail"
    - &jobAddition !Job
        name: "nextaddition"
        node: *node_pool
        schedule: !IntervalScheduler
            interval: 12s
        actions:
            - &actionAddition !Action
                name: "somenewshit"
                command: "sleep 4; echo jobs done"

